### ISSUE TITLE
Overall Damage Calc

### ISSUE THREAD

**Issue by Liamcedric** [Sokitas/Void-of-the-Dragons-Log-o-rama#2]
Not sure if you still update this. but the calculations for Overall Damage seem to be incorrect. It looks like Regular Hit damage is actually overall damage.

**Comment by Sokitas** [comment]
Hi there, 

to my chagrin you seem to be right. I simplified the way the values are calculated and now it should work as intended. Let me know if there are any more issues. 

I pushed a new release to include the fix (2.2).

Cheers.
